/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.dcsg.pc.eventing.schema.link;
@org.apache.avro.specific.AvroGenerated
public enum EntityLinkType implements org.apache.avro.generic.GenericEnumSymbol<EntityLinkType> {
  SkuToStyleLink, StyleToEcodeLink  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"EntityLinkType\",\"namespace\":\"com.dcsg.pc.eventing.schema.link\",\"symbols\":[\"SkuToStyleLink\",\"StyleToEcodeLink\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
