/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.dcsg.pc.eventing.schema.syndigopimcopy;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class EventMessageData extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 906424667733385090L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"EventMessageData\",\"namespace\":\"com.dcsg.pc.eventing.schema.syndigopimcopy\",\"fields\":[{\"name\":\"attributes\",\"type\":[\"null\",{\"type\":\"map\",\"values\":{\"type\":\"record\",\"name\":\"DataValues\",\"fields\":[{\"name\":\"group\",\"type\":[\"null\",{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"Group\",\"fields\":[{\"name\":\"valuesMap\",\"type\":{\"type\":\"map\",\"values\":\"DataValues\"}}]},\"java-class\":\"java.util.List\"}],\"default\":null},{\"name\":\"values\",\"type\":[\"null\",{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"AttributeValue\",\"fields\":[{\"name\":\"value\",\"type\":\"string\"}]},\"java-class\":\"java.util.List\"}],\"default\":null}]}}],\"default\":null},{\"name\":\"relationships\",\"type\":[\"null\",{\"type\":\"map\",\"values\":{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"RelationshipLink\",\"fields\":[{\"name\":\"attributes\",\"type\":[\"null\",{\"type\":\"map\",\"values\":\"DataValues\"}]},{\"name\":\"relTo\",\"type\":{\"type\":\"record\",\"name\":\"Link\",\"fields\":[{\"name\":\"data\",\"type\":[\"null\",{\"type\":\"record\",\"name\":\"RelationshipData\",\"fields\":[{\"name\":\"attributes\",\"type\":{\"type\":\"map\",\"values\":\"DataValues\"}}]}],\"default\":null},{\"name\":\"id\",\"type\":\"string\"},{\"name\":\"type\",\"type\":\"string\"}]}}]},\"java-class\":\"java.util.List\"}}],\"default\":null}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<EventMessageData> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<EventMessageData> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<EventMessageData> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<EventMessageData> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<EventMessageData> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this EventMessageData to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a EventMessageData from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a EventMessageData instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static EventMessageData fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.util.Map<java.lang.CharSequence,com.dcsg.pc.eventing.schema.syndigopimcopy.DataValues> attributes;
  private java.util.Map<java.lang.CharSequence,java.util.List<com.dcsg.pc.eventing.schema.syndigopimcopy.RelationshipLink>> relationships;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public EventMessageData() {}

  /**
   * All-args constructor.
   * @param attributes The new value for attributes
   * @param relationships The new value for relationships
   */
  public EventMessageData(java.util.Map<java.lang.CharSequence,com.dcsg.pc.eventing.schema.syndigopimcopy.DataValues> attributes, java.util.Map<java.lang.CharSequence,java.util.List<com.dcsg.pc.eventing.schema.syndigopimcopy.RelationshipLink>> relationships) {
    this.attributes = attributes;
    this.relationships = relationships;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return attributes;
    case 1: return relationships;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: attributes = (java.util.Map<java.lang.CharSequence,com.dcsg.pc.eventing.schema.syndigopimcopy.DataValues>)value$; break;
    case 1: relationships = (java.util.Map<java.lang.CharSequence,java.util.List<com.dcsg.pc.eventing.schema.syndigopimcopy.RelationshipLink>>)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'attributes' field.
   * @return The value of the 'attributes' field.
   */
  public java.util.Map<java.lang.CharSequence,com.dcsg.pc.eventing.schema.syndigopimcopy.DataValues> getAttributes() {
    return attributes;
  }


  /**
   * Sets the value of the 'attributes' field.
   * @param value the value to set.
   */
  public void setAttributes(java.util.Map<java.lang.CharSequence,com.dcsg.pc.eventing.schema.syndigopimcopy.DataValues> value) {
    this.attributes = value;
  }

  /**
   * Gets the value of the 'relationships' field.
   * @return The value of the 'relationships' field.
   */
  public java.util.Map<java.lang.CharSequence,java.util.List<com.dcsg.pc.eventing.schema.syndigopimcopy.RelationshipLink>> getRelationships() {
    return relationships;
  }


  /**
   * Sets the value of the 'relationships' field.
   * @param value the value to set.
   */
  public void setRelationships(java.util.Map<java.lang.CharSequence,java.util.List<com.dcsg.pc.eventing.schema.syndigopimcopy.RelationshipLink>> value) {
    this.relationships = value;
  }

  /**
   * Creates a new EventMessageData RecordBuilder.
   * @return A new EventMessageData RecordBuilder
   */
  public static com.dcsg.pc.eventing.schema.syndigopimcopy.EventMessageData.Builder newBuilder() {
    return new com.dcsg.pc.eventing.schema.syndigopimcopy.EventMessageData.Builder();
  }

  /**
   * Creates a new EventMessageData RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new EventMessageData RecordBuilder
   */
  public static com.dcsg.pc.eventing.schema.syndigopimcopy.EventMessageData.Builder newBuilder(com.dcsg.pc.eventing.schema.syndigopimcopy.EventMessageData.Builder other) {
    if (other == null) {
      return new com.dcsg.pc.eventing.schema.syndigopimcopy.EventMessageData.Builder();
    } else {
      return new com.dcsg.pc.eventing.schema.syndigopimcopy.EventMessageData.Builder(other);
    }
  }

  /**
   * Creates a new EventMessageData RecordBuilder by copying an existing EventMessageData instance.
   * @param other The existing instance to copy.
   * @return A new EventMessageData RecordBuilder
   */
  public static com.dcsg.pc.eventing.schema.syndigopimcopy.EventMessageData.Builder newBuilder(com.dcsg.pc.eventing.schema.syndigopimcopy.EventMessageData other) {
    if (other == null) {
      return new com.dcsg.pc.eventing.schema.syndigopimcopy.EventMessageData.Builder();
    } else {
      return new com.dcsg.pc.eventing.schema.syndigopimcopy.EventMessageData.Builder(other);
    }
  }

  /**
   * RecordBuilder for EventMessageData instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<EventMessageData>
    implements org.apache.avro.data.RecordBuilder<EventMessageData> {

    private java.util.Map<java.lang.CharSequence,com.dcsg.pc.eventing.schema.syndigopimcopy.DataValues> attributes;
    private java.util.Map<java.lang.CharSequence,java.util.List<com.dcsg.pc.eventing.schema.syndigopimcopy.RelationshipLink>> relationships;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.dcsg.pc.eventing.schema.syndigopimcopy.EventMessageData.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.attributes)) {
        this.attributes = data().deepCopy(fields()[0].schema(), other.attributes);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.relationships)) {
        this.relationships = data().deepCopy(fields()[1].schema(), other.relationships);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
    }

    /**
     * Creates a Builder by copying an existing EventMessageData instance
     * @param other The existing instance to copy.
     */
    private Builder(com.dcsg.pc.eventing.schema.syndigopimcopy.EventMessageData other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.attributes)) {
        this.attributes = data().deepCopy(fields()[0].schema(), other.attributes);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.relationships)) {
        this.relationships = data().deepCopy(fields()[1].schema(), other.relationships);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'attributes' field.
      * @return The value.
      */
    public java.util.Map<java.lang.CharSequence,com.dcsg.pc.eventing.schema.syndigopimcopy.DataValues> getAttributes() {
      return attributes;
    }


    /**
      * Sets the value of the 'attributes' field.
      * @param value The value of 'attributes'.
      * @return This builder.
      */
    public com.dcsg.pc.eventing.schema.syndigopimcopy.EventMessageData.Builder setAttributes(java.util.Map<java.lang.CharSequence,com.dcsg.pc.eventing.schema.syndigopimcopy.DataValues> value) {
      validate(fields()[0], value);
      this.attributes = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'attributes' field has been set.
      * @return True if the 'attributes' field has been set, false otherwise.
      */
    public boolean hasAttributes() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'attributes' field.
      * @return This builder.
      */
    public com.dcsg.pc.eventing.schema.syndigopimcopy.EventMessageData.Builder clearAttributes() {
      attributes = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'relationships' field.
      * @return The value.
      */
    public java.util.Map<java.lang.CharSequence,java.util.List<com.dcsg.pc.eventing.schema.syndigopimcopy.RelationshipLink>> getRelationships() {
      return relationships;
    }


    /**
      * Sets the value of the 'relationships' field.
      * @param value The value of 'relationships'.
      * @return This builder.
      */
    public com.dcsg.pc.eventing.schema.syndigopimcopy.EventMessageData.Builder setRelationships(java.util.Map<java.lang.CharSequence,java.util.List<com.dcsg.pc.eventing.schema.syndigopimcopy.RelationshipLink>> value) {
      validate(fields()[1], value);
      this.relationships = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'relationships' field has been set.
      * @return True if the 'relationships' field has been set, false otherwise.
      */
    public boolean hasRelationships() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'relationships' field.
      * @return This builder.
      */
    public com.dcsg.pc.eventing.schema.syndigopimcopy.EventMessageData.Builder clearRelationships() {
      relationships = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public EventMessageData build() {
      try {
        EventMessageData record = new EventMessageData();
        record.attributes = fieldSetFlags()[0] ? this.attributes : (java.util.Map<java.lang.CharSequence,com.dcsg.pc.eventing.schema.syndigopimcopy.DataValues>) defaultValue(fields()[0]);
        record.relationships = fieldSetFlags()[1] ? this.relationships : (java.util.Map<java.lang.CharSequence,java.util.List<com.dcsg.pc.eventing.schema.syndigopimcopy.RelationshipLink>>) defaultValue(fields()[1]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<EventMessageData>
    WRITER$ = (org.apache.avro.io.DatumWriter<EventMessageData>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<EventMessageData>
    READER$ = (org.apache.avro.io.DatumReader<EventMessageData>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    if (this.attributes == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      long size0 = this.attributes.size();
      out.writeMapStart();
      out.setItemCount(size0);
      long actualSize0 = 0;
      for (java.util.Map.Entry<java.lang.CharSequence, com.dcsg.pc.eventing.schema.syndigopimcopy.DataValues> e0: this.attributes.entrySet()) {
        actualSize0++;
        out.startItem();
        out.writeString(e0.getKey());
        com.dcsg.pc.eventing.schema.syndigopimcopy.DataValues v0 = e0.getValue();
        v0.customEncode(out);
      }
      out.writeMapEnd();
      if (actualSize0 != size0)
      throw new java.util.ConcurrentModificationException("Map-size written was " + size0 + ", but element count was " + actualSize0 + ".");
    }

    if (this.relationships == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      long size1 = this.relationships.size();
      out.writeMapStart();
      out.setItemCount(size1);
      long actualSize1 = 0;
      for (java.util.Map.Entry<java.lang.CharSequence, java.util.List<com.dcsg.pc.eventing.schema.syndigopimcopy.RelationshipLink>> e1: this.relationships.entrySet()) {
        actualSize1++;
        out.startItem();
        out.writeString(e1.getKey());
        java.util.List<com.dcsg.pc.eventing.schema.syndigopimcopy.RelationshipLink> v1 = e1.getValue();
        long size2 = v1.size();
        out.writeArrayStart();
        out.setItemCount(size2);
        long actualSize2 = 0;
        for (com.dcsg.pc.eventing.schema.syndigopimcopy.RelationshipLink e2: v1) {
          actualSize2++;
          out.startItem();
          e2.customEncode(out);
        }
        out.writeArrayEnd();
        if (actualSize2 != size2)
          throw new java.util.ConcurrentModificationException("Array-size written was " + size2 + ", but element count was " + actualSize2 + ".");
      }
      out.writeMapEnd();
      if (actualSize1 != size1)
      throw new java.util.ConcurrentModificationException("Map-size written was " + size1 + ", but element count was " + actualSize1 + ".");
    }

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      if (in.readIndex() != 1) {
        in.readNull();
        this.attributes = null;
      } else {
        long size0 = in.readMapStart();
        java.util.Map<java.lang.CharSequence,com.dcsg.pc.eventing.schema.syndigopimcopy.DataValues> m0 = this.attributes; // Need fresh name due to limitation of macro system
        if (m0 == null) {
          m0 = new java.util.HashMap<java.lang.CharSequence,com.dcsg.pc.eventing.schema.syndigopimcopy.DataValues>((int)size0);
          this.attributes = m0;
        } else m0.clear();
        for ( ; 0 < size0; size0 = in.mapNext()) {
          for ( ; size0 != 0; size0--) {
            java.lang.CharSequence k0 = null;
            k0 = in.readString(k0 instanceof Utf8 ? (Utf8)k0 : null);
            com.dcsg.pc.eventing.schema.syndigopimcopy.DataValues v0 = null;
            if (v0 == null) {
              v0 = new com.dcsg.pc.eventing.schema.syndigopimcopy.DataValues();
            }
            v0.customDecode(in);
            m0.put(k0, v0);
          }
        }
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.relationships = null;
      } else {
        long size1 = in.readMapStart();
        java.util.Map<java.lang.CharSequence,java.util.List<com.dcsg.pc.eventing.schema.syndigopimcopy.RelationshipLink>> m1 = this.relationships; // Need fresh name due to limitation of macro system
        if (m1 == null) {
          m1 = new java.util.HashMap<java.lang.CharSequence,java.util.List<com.dcsg.pc.eventing.schema.syndigopimcopy.RelationshipLink>>((int)size1);
          this.relationships = m1;
        } else m1.clear();
        for ( ; 0 < size1; size1 = in.mapNext()) {
          for ( ; size1 != 0; size1--) {
            java.lang.CharSequence k1 = null;
            k1 = in.readString(k1 instanceof Utf8 ? (Utf8)k1 : null);
            java.util.List<com.dcsg.pc.eventing.schema.syndigopimcopy.RelationshipLink> v1 = null;
            long size2 = in.readArrayStart();
            java.util.List<com.dcsg.pc.eventing.schema.syndigopimcopy.RelationshipLink> a2 = v1;
            if (a2 == null) {
              a2 = new SpecificData.Array<com.dcsg.pc.eventing.schema.syndigopimcopy.RelationshipLink>((int)size2, SCHEMA$.getField("relationships").schema().getTypes().get(1).getValueType());
              v1 = a2;
            } else a2.clear();
            SpecificData.Array<com.dcsg.pc.eventing.schema.syndigopimcopy.RelationshipLink> ga2 = (a2 instanceof SpecificData.Array ? (SpecificData.Array<com.dcsg.pc.eventing.schema.syndigopimcopy.RelationshipLink>)a2 : null);
            for ( ; 0 < size2; size2 = in.arrayNext()) {
              for ( ; size2 != 0; size2--) {
                com.dcsg.pc.eventing.schema.syndigopimcopy.RelationshipLink e2 = (ga2 != null ? ga2.peek() : null);
                if (e2 == null) {
                  e2 = new com.dcsg.pc.eventing.schema.syndigopimcopy.RelationshipLink();
                }
                e2.customDecode(in);
                a2.add(e2);
              }
            }
            m1.put(k1, v1);
          }
        }
      }

    } else {
      for (int i = 0; i < 2; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          if (in.readIndex() != 1) {
            in.readNull();
            this.attributes = null;
          } else {
            long size0 = in.readMapStart();
            java.util.Map<java.lang.CharSequence,com.dcsg.pc.eventing.schema.syndigopimcopy.DataValues> m0 = this.attributes; // Need fresh name due to limitation of macro system
            if (m0 == null) {
              m0 = new java.util.HashMap<java.lang.CharSequence,com.dcsg.pc.eventing.schema.syndigopimcopy.DataValues>((int)size0);
              this.attributes = m0;
            } else m0.clear();
            for ( ; 0 < size0; size0 = in.mapNext()) {
              for ( ; size0 != 0; size0--) {
                java.lang.CharSequence k0 = null;
                k0 = in.readString(k0 instanceof Utf8 ? (Utf8)k0 : null);
                com.dcsg.pc.eventing.schema.syndigopimcopy.DataValues v0 = null;
                if (v0 == null) {
                  v0 = new com.dcsg.pc.eventing.schema.syndigopimcopy.DataValues();
                }
                v0.customDecode(in);
                m0.put(k0, v0);
              }
            }
          }
          break;

        case 1:
          if (in.readIndex() != 1) {
            in.readNull();
            this.relationships = null;
          } else {
            long size1 = in.readMapStart();
            java.util.Map<java.lang.CharSequence,java.util.List<com.dcsg.pc.eventing.schema.syndigopimcopy.RelationshipLink>> m1 = this.relationships; // Need fresh name due to limitation of macro system
            if (m1 == null) {
              m1 = new java.util.HashMap<java.lang.CharSequence,java.util.List<com.dcsg.pc.eventing.schema.syndigopimcopy.RelationshipLink>>((int)size1);
              this.relationships = m1;
            } else m1.clear();
            for ( ; 0 < size1; size1 = in.mapNext()) {
              for ( ; size1 != 0; size1--) {
                java.lang.CharSequence k1 = null;
                k1 = in.readString(k1 instanceof Utf8 ? (Utf8)k1 : null);
                java.util.List<com.dcsg.pc.eventing.schema.syndigopimcopy.RelationshipLink> v1 = null;
                long size2 = in.readArrayStart();
                java.util.List<com.dcsg.pc.eventing.schema.syndigopimcopy.RelationshipLink> a2 = v1;
                if (a2 == null) {
                  a2 = new SpecificData.Array<com.dcsg.pc.eventing.schema.syndigopimcopy.RelationshipLink>((int)size2, SCHEMA$.getField("relationships").schema().getTypes().get(1).getValueType());
                  v1 = a2;
                } else a2.clear();
                SpecificData.Array<com.dcsg.pc.eventing.schema.syndigopimcopy.RelationshipLink> ga2 = (a2 instanceof SpecificData.Array ? (SpecificData.Array<com.dcsg.pc.eventing.schema.syndigopimcopy.RelationshipLink>)a2 : null);
                for ( ; 0 < size2; size2 = in.arrayNext()) {
                  for ( ; size2 != 0; size2--) {
                    com.dcsg.pc.eventing.schema.syndigopimcopy.RelationshipLink e2 = (ga2 != null ? ga2.peek() : null);
                    if (e2 == null) {
                      e2 = new com.dcsg.pc.eventing.schema.syndigopimcopy.RelationshipLink();
                    }
                    e2.customDecode(in);
                    a2.add(e2);
                  }
                }
                m1.put(k1, v1);
              }
            }
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










