/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.dcsg.pc.eventing.schema.common;
@org.apache.avro.specific.AvroGenerated
public enum RecordStatus implements org.apache.avro.generic.GenericEnumSymbol<RecordStatus> {
  ACTIVE, DELETED  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"RecordStatus\",\"namespace\":\"com.dcsg.pc.eventing.schema.common\",\"symbols\":[\"ACTIVE\",\"DELETED\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
