/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.dcsg.pc.eventing.schema.completion;
@org.apache.avro.specific.AvroGenerated
public enum actionType implements org.apache.avro.generic.GenericEnumSymbol<actionType> {
  create, update, unknown  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"actionType\",\"namespace\":\"com.dcsg.pc.eventing.schema.completion\",\"symbols\":[\"create\",\"update\",\"unknown\"],\"default\":\"unknown\"}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
