/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.dcsg.pc.eventing.schema.completion;
@org.apache.avro.specific.AvroGenerated
public enum entityType implements org.apache.avro.generic.GenericEnumSymbol<entityType> {
  sku, style, ecode, unknown  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"entityType\",\"namespace\":\"com.dcsg.pc.eventing.schema.completion\",\"symbols\":[\"sku\",\"style\",\"ecode\",\"unknown\"],\"default\":\"unknown\"}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
